language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
install: npm install
before_script:
  - grunt coffeelint
  # angular
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start
after_success:
  - cat ./coverage/sails-lcov.info | ./node_modules/coveralls/bin/coveralls.js –
